### PR TITLE
v2 upgrade

### PR DESCRIPTION
**Pull request by sumpygump**
Hello there!

The Tiny Tricks VCV modules are neat, I thought I would take a look at what it would take to upgrade them to work with version 2 of Rack. I opted to update the version to 2.5.0 (skip from 1.5.0 to 2.5.0).

(I used https://vcvrack.com/manual/Migrate2 as a guide)

The actual upgrade was very simple, there were only a few minor changes required as completed in the first commit.

In the second commit I utilized the new configSwitch(), configInput(), configOutput() and configButton() functions to make the right click menu on inputs, outputs and switches have the additional labeling and functionality.

I tested out each module using Rack 2 build Rack-SDK-2.git.219bbaf1-mac (from 10/17/2021).

I also noticed some inconsistencies with the indentation (tabs vs spaces), some spacing around braces and cleaned it up using astyle. I ran astyle with the following `.astylerc` options:

```
# astyle settings file

# Requires Artistic Style 3.1
# http://astyle.sourceforge.net/

# Usage:
# astyle --suffix=none --options=.astylerc filename.cpp
# or recursively
# astyle --suffix=none --options=.astylerc -r 'include/*' 'src/*'
# or using find
# find src include -type f | xargs astyle --suffix=none --options=.astylerc

style=java
indent=spaces=2
attach-closing-while
indent-classes
indent-switches
indent-preproc-block
indent-preproc-define
indent-col1-comments
pad-oper
pad-comma
pad-header
unpad-paren
align-pointer=name
align-reference=name
break-closing-braces
break-one-line-headers
attach-return-type
attach-return-type-decl
keep-one-line-statements
close-templates
```

### CODE REVIEW

**Comment by thomassidor** [comment]
Hi Jansen

Amazing work!

I'll commit it to the base branch and update the documentation on here.

If you'd like I can add you as a collaborator to the project so you can push updates and so on as you like. I don't really have any plans to keep maintaining or extending this, so anyone who want to contribute are very welcome.

All the best, Thomas

**Comment by stephanepericat** [comment]
Do you know when this update will be published ? I use these plugins a lot :)

**Comment by sumpygump** [comment]
Hopefully soon

**Comment by sumpygump** [comment]
Stéphane, Tiny Tricks is now available in the Rack 2 library. Enjoy!

**Comment by stephanepericat** [comment]
Thanks !!!

**Pull request merged**
