### PR TITLE
Fix RandomWrangler crashes

### LINKED ISSUE #24: VCV Rack Free v2.0.3 - Random Wrangler crashing
I wanted to select Random Wrangler (RW) in the Rack plugin browser but it crashed. I use v2.0.3 under Win10. 

The last few lines of the log.txt look like this:
`C:/Users/aszabo/Documents/Rack2/plugins/CountModula/res/G2T.svg
[8.347 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/components/PortLight.svg
[8.347 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/RoundSmallBlackKnob.svg
[8.348 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/RoundSmallBlackKnob_bg.svg
[8.349 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTTRI.svg
[8.350 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/ScrewBlack.svg
[8.358 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RW.svg
[8.358 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/LargeLight.svg
[8.359 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSQRPLUS.svg
[8.359 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTA.svg
[8.360 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSIN.svg
[8.360 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/A8.svg
[8.361 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSQR.svg
[8.361 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RX8.svg
[8.362 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RM8S.svg
[8.363 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSAWPLUS.svg
[8.394 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO8.svg
[8.395 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSINPLUS.svg
[8.396 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTTRIPLUS.svg
[8.396 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO16.svg
[8.397 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/SH16.svg
[8.425 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSAW.svg
[8.425 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO1.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/components/Wavetable.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_0.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_1.svg
[8.427 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_2.svg
[8.428 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/WAVE.svg
[10.240 fatal adapters/standalone.cpp:60 fatalSignalHandler] Fatal signal 22 SIG. Stack trace:
36:  0x0
35: raise 0x7fffc100ac60
34: abort 0x7fffc100f270
33: ZN9TTLWidgetD1Ev 0xcae8f0
32: ZN10WAVEWidgetD1Ev 0xc7ecf0
31: ZSt7shuffleIN9__gnu_cxx17__normal_iteratorIPiSt6vectorIiSaIiEEEERSt26linear_congruential_engineIjLj16807ELj0ELj2147483647EEEvT_SA_OT0_ 0xd3f980
30: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0xd4e000
29: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0xd4e000
28: ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_ 0xd2e5f0
27: ZN14RANDOMWRANGLERC1Ev 0xc8ada0
26: ZZN4rack11createModelI14RANDOMWRANGLER20RANDOMWRANGLERWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel12createModuleEv 0xd46a40
25: ZN4rack3app11AudioButton8onActionERKNS_6widget6Widget11ActionEventE 0x7fff48faca30
24: ZN4rack3app7browser8ModelBox8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff4944b390
23: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
22: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
21: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
20: ZN4rack2ui12ScrollWidget8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff48fed900
19: ZN4rack3app7browser7Browser8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff49449290
18: ZN4rack2ui11MenuOverlay8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff48fec8e0
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS0_6Widget11ButtonEventE 0x7fff49471080
16: ZN4rack6widget10EventState12handleButtonENS_4math3VecEiii 0x7fff48ff1b30
15: ZN4rack6window3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x7fff48ff6bc0
14: glfwPlatformUnlockMutex 0x7fff49033f20
13: CallWindowProcW 0x7fffc18f5850
12: CallWindowProcW 0x7fffc18f5850
11: glPushClientAttrib 0x7fff88a53770
10: CallWindowProcW 0x7fffc18f5850
9: DispatchMessageW 0x7fffc18f5410
8: glfwPlatformPollEvents 0x7fff49037920
7: ZN4rack6window6Window4stepEv 0x7fff48ff7f00
6: ZN4rack6window6Window3runEv 0x7fff48ff88c0
5: ZN4rack6window6Window3runEv 0x7fff48ff88c0
4: ZN4rack6window6Window3runEv 0x7fff48ff88c0
3: ZN4rack6window6Window3runEv 0x7fff48ff88c0
2: ZN4rack6window6Window3runEv 0x7fff48ff88c0
1: BaseThreadInitThunk 0x7fffc1ba7c10
0: RtlUserThreadStart 0x7fffc2fad700
`
(Other modules like SH16, SN-OSC, A8 work all fine for me.)

### PR DESCRIPTION
**Pull request by baconpaul**
1. Update configParam to the intended configSwitch
2. In dataFromJSON check for null curve widget
3. Add a .gitignore entry for ARM64 builds. Also it seems to compile just fine on ARM64

Closes #24, #27

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi! Just cleaning up my GitHub. I'm assuming this repo is no longer monitored and the project is abandoned, but if not, wondering if you either want to merge this? I'll close it next week if I don't hear.

Thanks!

**Comment by thomassidor** [comment]
Hi Paul

Yeah, I'm not doing any more work on this project.

I'll gladly hand over full ownership of it.

All the best, Thomas

**Comment by baconpaul** [comment]
OK!  Let me think if i have bandwidth to merge, release, etc.... and if vcv would let me given i've written a bit of these and your statement above. I'll leave this open for now. Thanks!

**Comment by thomassidor** [comment]
Ok. Let me know if there's anything practical I need to do to hand stuff over to you.

**Comment by baconpaul** [comment]
Awesome i see you gave me access. Lemme see if I can do everything Ineed to do a point release with that fix in place without you doing anything. I'll tag you if i get stuck but it all looks like we should be fine to me.

And thanks! Hope things are going well with all your non-rack projects and activities. Thanks for giving me perms here.

**Pull request merged**
